version: '3.3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
      - --spi-events-listener-gdpr-jboss-logging-success-level=info 
      - --spi-events-listener-gdpr-jboss-logging-error-level=error
    volumes:
      - ./build/libs:/opt/keycloak/providers